# Generated by Django 5.0 on 2024-04-04 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safglobalcrm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubadditionalofficeaddress',
            name='hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addtionalAddresses', to='safglobalcrm.hubs'),
        ),
        migrations.AlterField(
            model_name='hubemails',
            name='hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='safglobalcrm.hubs'),
        ),
    ]
