# Generated by Django 5.0 on 2024-04-04 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safglobalcrm', '0003_alter_hubadditionalofficeaddress_hub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubemailsettings',
            name='hub',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safglobalcrm.hubs'),
        ),
    ]
