# Generated by Django 5.0 on 2024-04-08 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safglobalcrm', '0004_alter_hubemailsettings_hub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentconsignee',
            name='consignee_in',
        ),
        migrations.RemoveField(
            model_name='shipmentdeparture',
            name='departure_in',
        ),
        migrations.AddField(
            model_name='shipment',
            name='consignee_in',
            field=models.CharField(choices=[('H', 'Hub'), ('O', 'Office'), ('A', 'Agent')], default='O', max_length=2),
        ),
        migrations.AddField(
            model_name='shipment',
            name='departure_in',
            field=models.CharField(choices=[('H', 'Hub'), ('O', 'Office'), ('A', 'Agent')], default='O', max_length=2),
        ),
        migrations.AlterField(
            model_name='agentadditionalofficeaddress',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additionalAddresses', to='safglobalcrm.agents'),
        ),
        migrations.AlterField(
            model_name='agentemails',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='safglobalcrm.agents'),
        ),
        migrations.AlterField(
            model_name='customeremails',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='safglobalcrm.customers'),
        ),
        migrations.AlterField(
            model_name='customerpostaladdress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additionalAddresses', to='safglobalcrm.customers'),
        ),
        migrations.AlterField(
            model_name='othercompaniesadditionalofficeaddress',
            name='other_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additionalAddresses', to='safglobalcrm.othercompanies'),
        ),
        migrations.AlterField(
            model_name='othercompanyemails',
            name='other_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='safglobalcrm.othercompanies'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='consignee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='safglobalcrm.shipmentconsignee'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='departure',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='safglobalcrm.shipmentdeparture'),
        ),
        migrations.AlterField(
            model_name='supplieradditionalofficeaddress',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additionalAddresses', to='safglobalcrm.suppliers'),
        ),
        migrations.AlterField(
            model_name='supplieremails',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='safglobalcrm.suppliers'),
        ),
    ]
