# Generated by Django 5.0 on 2024-04-08 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safglobalcrm', '0005_remove_shipmentconsignee_consignee_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='consignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safglobalcrm.shipmentconsignee'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='consignee_in',
            field=models.CharField(choices=[('H', 'Hub'), ('O', 'Office'), ('A', 'Agent')], max_length=2),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='departure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safglobalcrm.shipmentdeparture'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='departure_in',
            field=models.CharField(choices=[('H', 'Hub'), ('O', 'Office'), ('A', 'Agent')], max_length=2),
        ),
    ]
