# Generated by Django 5.0 on 2024-04-10 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safglobalcrm', '0006_alter_shipment_consignee_alter_shipment_consignee_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Air',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airway_bill', models.CharField(max_length=100)),
                ('flt_no', models.CharField(max_length=100)),
                ('dep_dt', models.CharField(max_length=100)),
                ('arr_dt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Coriers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill', models.CharField(max_length=100)),
                ('carrier', models.CharField(max_length=100)),
                ('dep_dt', models.CharField(max_length=100)),
                ('arr_dt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CRRDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='uploads/crr/documents')),
            ],
        ),
        migrations.CreateModel(
            name='CRRStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('cbm', models.CharField(max_length=100)),
                ('warhouse_location', models.TextField()),
                ('dgr', models.BooleanField(default=False)),
                ('not_stack', models.BooleanField(default=False)),
                ('medicine', models.BooleanField(default=False)),
                ('x_ray', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OnBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_dt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freight_company', models.CharField(max_length=100)),
                ('dep_dt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_bill', models.CharField(max_length=100)),
                ('Vessel_voy', models.CharField(max_length=100)),
                ('etd', models.CharField(max_length=100)),
                ('eta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmr', models.CharField(max_length=100)),
                ('freight_company', models.CharField(max_length=100)),
                ('dep_dt', models.CharField(max_length=100)),
                ('arr_dt', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='shipment',
            name='mark_as_arrived',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='service',
            field=models.CharField(choices=[('A', 'Air'), ('S', 'Sea'), ('T', 'Truck'), ('C', 'Coriers'), ('R', 'Release'), ('O', 'On Board')], max_length=1),
        ),
        migrations.CreateModel(
            name='CRR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=20)),
                ('po_remarks', models.TextField()),
                ('content', models.TextField()),
                ('content_description', models.TextField()),
                ('expected_delivery_date', models.DateField()),
                ('actual_delivery_date', models.DateField(null=True)),
                ('supplier_reference', models.TextField()),
                ('deadline_warehouse', models.DateField()),
                ('internal_shipment', models.TextField()),
                ('delivery_irregulations', models.TextField()),
                ('transit_id', models.CharField(max_length=20)),
                ('t1_reference', models.CharField(max_length=150)),
                ('ex_a', models.CharField(max_length=150)),
                ('hs_code', models.CharField(max_length=150)),
                ('customs_value', models.TextField()),
                ('priorty', models.TextField()),
                ('customs_value_usd', models.TextField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('D', 'Delivered'), ('O', 'On Call')], max_length=1)),
                ('accept', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='safglobalcrm.agents')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='safglobalcrm.countries')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='safglobalcrm.currencies')),
                ('hub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='safglobalcrm.hubs')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safglobalcrm.suppliers')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safglobalcrm.customervessels')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentServiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='safglobalcrm.air')),
                ('coriers', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='safglobalcrm.coriers')),
                ('on_board', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='safglobalcrm.onboard')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='safglobalcrm.release')),
                ('sea', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='safglobalcrm.sea')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safglobalcrm.shipment')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='safglobalcrm.truck')),
            ],
        ),
    ]
