# Generated by Django 5.0 on 2024-04-10 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safglobalcrm', '0007_air_coriers_crrdocuments_crrstockitem_onboard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentservicedetails',
            name='air',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='safglobalcrm.air'),
        ),
        migrations.AlterField(
            model_name='shipmentservicedetails',
            name='coriers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='safglobalcrm.coriers'),
        ),
        migrations.AlterField(
            model_name='shipmentservicedetails',
            name='on_board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='safglobalcrm.onboard'),
        ),
        migrations.AlterField(
            model_name='shipmentservicedetails',
            name='release',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='safglobalcrm.release'),
        ),
        migrations.AlterField(
            model_name='shipmentservicedetails',
            name='sea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='safglobalcrm.sea'),
        ),
        migrations.AlterField(
            model_name='shipmentservicedetails',
            name='truck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='safglobalcrm.truck'),
        ),
    ]
