# Generated by Django 5.0 on 2024-04-11 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safglobalcrm', '0010_alter_crrdocuments_crr_alter_crrstockitem_crr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crrdocuments',
            name='crr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safglobalcrm.crr'),
        ),
        migrations.AlterField(
            model_name='crrstockitem',
            name='crr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safglobalcrm.crr'),
        ),
    ]
