# Generated by Django 5.0 on 2024-06-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safglobalcrm', '0011_alter_crrdocuments_crr_alter_crrstockitem_crr'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubs',
            name='eori_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hubs',
            name='un_lo_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
