# Generated by Django 5.0 on 2024-06-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safglobalcrm', '0012_hubs_eori_number_hubs_un_lo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='responsible_office',
            field=models.CharField(max_length=100),
        ),
    ]
