# Generated by Django 5.0.6 on 2024-07-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safglobalcrm', '0015_rename_is_gts_hubs_is_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='phonecode',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
