# Generated by Django 5.0.6 on 2024-07-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safglobalcrm', '0016_countries_phonecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='icon',
            field=models.ImageField(null=True, upload_to='uploads/icons/countries'),
        ),
    ]
