# Generated by Django 5.0.6 on 2024-07-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safglobalcrm', '0017_alter_countries_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='phonecode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
