# Generated by Django 5.0.6 on 2024-07-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safglobalcrm', '0020_alter_crr_po_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='un_lo_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hubs',
            name='customer_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='offices',
            name='customer_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='othercompanies',
            name='un_lo_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='un_lo_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
