# Generated by Django 5.0.6 on 2024-08-05 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safglobalcrm', '0021_alter_agents_un_lo_code_alter_hubs_customer_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customervessels',
            name='account_manager',
        ),
        migrations.AlterField(
            model_name='customervessels',
            name='fleet_category',
            field=models.CharField(choices=[('1', 'MV'), ('2', 'MT')], max_length=1),
        ),
        migrations.AlterField(
            model_name='customervessels',
            name='manager_from_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_account_manager', to='safglobalcrm.customerusers'),
        ),
        migrations.AddField(
            model_name='customervessels',
            name='account_manager',
            field=models.ManyToManyField(related_name='all_account_managers', to='safglobalcrm.customerusers'),
        ),
    ]
