# Generated by Django 5.0.6 on 2024-08-05 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safglobalcrm', '0022_remove_customervessels_account_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customervessels',
            name='account_manager',
            field=models.ManyToManyField(related_name='customer_vessels_list', to='safglobalcrm.customerusers'),
        ),
        migrations.AlterField(
            model_name='customervessels',
            name='manager_from_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='safglobalcrm.customerusers'),
        ),
    ]
