# Generated by Django 5.0.6 on 2024-08-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safglobalcrm', '0023_alter_customervessels_account_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crrdocuments',
            name='document_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
