# Generated by Django 5.0.6 on 2024-08-07 10:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safglobalcrm', '0025_crr_register_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='crr',
            name='register_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
