# Generated by Django 5.0.6 on 2024-08-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safglobalcrm', '0026_crr_register_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='stock_items',
            field=models.ManyToManyField(to='safglobalcrm.crr'),
        ),
    ]
