# Generated by Django 5.0.6 on 2024-09-03 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safglobalcrm', '0028_shipment_created_at_shipment_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
