# Generated by Django 5.0.6 on 2024-09-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safglobalcrm', '0031_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='changes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
